Get the supported storage tiers of a cloud instance
IBM-Cloud/power-go-client pull request #446
Opened 2024-08-17 06:55 UTC by kishen-v

Changes:
* Introduce a storage tier client to retrieve the storage tiers available to a associated cloud instance ID.

2024-08-17 06:55 UTC, kishen-v commented
cc @yussufsh

2024-08-17 13:05 UTC, yussufsh submitted a review, later dismissed
lgtm

2024-08-19 16:15 UTC, michaelkad requested changes
No need to pass the `id`

2024-08-19 16:15 UTC, michaelkad commented on clients/instance/ibm-pi-storage-tiers.go
> +func (f *IBMPIStorageTierClient) GetAll(id string) (models.RegionStorageTiers, error) {
```suggestion
func (f *IBMPIStorageTierClient) GetAll() (models.RegionStorageTiers, error) {
```

2024-08-19 16:15 UTC, michaelkad commented on clients/instance/ibm-pi-storage-tiers.go
> +		WithCloudInstanceID(id)
```suggestion
		WithCloudInstanceID(f.cloudInstanceID)
```

2024-08-20 04:46 UTC, kishen-v commented
Hi @michaelkad, thanks for reviewing the PR!

I have made the suggested changes. PTAL when time permits.

2024-08-20 13:13 UTC, michaelkad approved these changes

2024-08-20 15:41 UTC, merged