Q3 Release 2024
IBM-Cloud/power-go-client pull request #459
Opened 2024-09-10 19:27 UTC by ismirlia

Q3 release changes from dev branch that are going to production. Manually removed some q4 model changes that were made.

2024-09-10 20:03 UTC, Alexander-Kita submitted a review, later dismissed
Looks good, but wait for @michaelkad

2024-09-11 18:23 UTC, michaelkad approved these changes

2024-09-11 18:27 UTC, michaelkad requested changes
Can you add those back in?
```
// Bulk volume detach
func (f *IBMPIVolumeClient) BulkVolumeDetach(pvmID string, body *models.VolumesDetach) (*models.VolumesDetachmentResponse, error) {
	return nil, fmt.Errorf("operation not supported")
}

// Bulk volume delete
func (f *IBMPIVolumeClient) BulkVolumeDelete(body *models.VolumesDelete) (*models.VolumesDeleteResponse, error) {
	return nil, fmt.Errorf("operation not supported")
}
```
Those were done https://github.com/michaelkad/power-go-client/blob/add-volume-bulk-functions/clients/instance/ibm-pi-volume.go

2024-09-11 20:11 UTC, michaelkad approved these changes

2024-09-11 20:13 UTC, merged